version: "3"

services:
  fastapi:
    build: .
    ports:
      - "8002:8000"
    environment:
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: Fastapi-Auth
      SECRET_KEY: 621b41d58fe163991b9155a1d66096f57e01d8937d9fefe67655969965c1ac50
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_TIME: 5
      TOKEN_FETCH_URL: auth/token
    depends_on:
      - db

  db:
    image: postgres:13.20
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: Fastapi-Auth
    ports:
      - "8003:5432"
